// Seed the problem bank. ~120 Classic-mode problems across 8 tiers,
// covering arithmetic, algebra, geometry, trigonometry, precalculus,
// calculus, number theory, combinatorics, and probability.

import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

type Seed = {
  category: string;
  tier: string;
  difficultyElo: number;
  prompt: string;
  answerType: "numeric" | "multiple_choice";
  correctAnswer: string;
  acceptableForms?: string[];
  tolerance?: number;
  options?: string[];
  solution: string;
  timeLimitSeconds: number;
  calculatorAllowed?: boolean;
};

const PROBLEMS: Seed[] = [
  // ───────── Initiate (0–799) ─────────
  { category: "arithmetic", tier: "Initiate", difficultyElo: 400, prompt: "Compute $7 \\times 8$.", answerType: "numeric", correctAnswer: "56", solution: "$7 \\times 8 = 56$.", timeLimitSeconds: 30 },
  { category: "arithmetic", tier: "Initiate", difficultyElo: 420, prompt: "Compute $13 + 27$.", answerType: "numeric", correctAnswer: "40", solution: "$13 + 27 = 40$.", timeLimitSeconds: 30 },
  { category: "arithmetic", tier: "Initiate", difficultyElo: 440, prompt: "Compute $100 - 37$.", answerType: "numeric", correctAnswer: "63", solution: "$100 - 37 = 63$.", timeLimitSeconds: 30 },
  { category: "arithmetic", tier: "Initiate", difficultyElo: 470, prompt: "Compute $9 \\times 12$.", answerType: "numeric", correctAnswer: "108", solution: "$9 \\times 12 = 108$.", timeLimitSeconds: 30 },
  { category: "arithmetic", tier: "Initiate", difficultyElo: 500, prompt: "What is $\\dfrac{3}{4} + \\dfrac{1}{2}$? Enter as a decimal or fraction.", answerType: "numeric", correctAnswer: "1.25", acceptableForms: ["5/4", "1 1/4", "1.25"], tolerance: 1e-6, solution: "$\\dfrac{3}{4} + \\dfrac{2}{4} = \\dfrac{5}{4} = 1.25$.", timeLimitSeconds: 45 },
  { category: "arithmetic", tier: "Initiate", difficultyElo: 520, prompt: "Compute $\\dfrac{2}{3} \\times \\dfrac{3}{8}$.", answerType: "numeric", correctAnswer: "0.25", acceptableForms: ["1/4", "0.25"], tolerance: 1e-6, solution: "$\\dfrac{2 \\cdot 3}{3 \\cdot 8} = \\dfrac{1}{4}$.", timeLimitSeconds: 45 },
  { category: "arithmetic", tier: "Initiate", difficultyElo: 550, prompt: "What is $30\\%$ of $80$?", answerType: "numeric", correctAnswer: "24", solution: "$0.30 \\cdot 80 = 24$.", timeLimitSeconds: 45 },
  { category: "arithmetic", tier: "Initiate", difficultyElo: 580, prompt: "What is $\\dfrac{144}{12}$?", answerType: "numeric", correctAnswer: "12", solution: "$144 / 12 = 12$.", timeLimitSeconds: 30 },
  { category: "arithmetic", tier: "Initiate", difficultyElo: 600, prompt: "If a shirt costs \\$24 and is 25\\% off, how many dollars do you pay?", answerType: "numeric", correctAnswer: "18", solution: "$24 \\times 0.75 = 18$.", timeLimitSeconds: 60 },
  { category: "arithmetic", tier: "Initiate", difficultyElo: 620, prompt: "A pizza is cut into 8 equal slices. You eat 3. What fraction is left? Enter as decimal.", answerType: "numeric", correctAnswer: "0.625", acceptableForms: ["5/8", "0.625"], tolerance: 1e-6, solution: "$1 - 3/8 = 5/8 = 0.625$.", timeLimitSeconds: 45 },
  { category: "arithmetic", tier: "Initiate", difficultyElo: 650, prompt: "Pick: $-7 + 12 = $", answerType: "multiple_choice", correctAnswer: "5", options: ["-19", "-5", "5", "19"], solution: "$-7 + 12 = 5$.", timeLimitSeconds: 30 },
  { category: "arithmetic", tier: "Initiate", difficultyElo: 680, prompt: "What is $\\sqrt{81}$?", answerType: "numeric", correctAnswer: "9", solution: "$9^2 = 81$.", timeLimitSeconds: 30 },
  { category: "arithmetic", tier: "Initiate", difficultyElo: 700, prompt: "What is $\\sqrt{144}$?", answerType: "numeric", correctAnswer: "12", solution: "$12 \\times 12 = 144$.", timeLimitSeconds: 30 },
  { category: "arithmetic", tier: "Initiate", difficultyElo: 720, prompt: "Compute $2^5$.", answerType: "numeric", correctAnswer: "32", solution: "$2^5 = 32$.", timeLimitSeconds: 30 },
  { category: "arithmetic", tier: "Initiate", difficultyElo: 750, prompt: "Pick the correct value of $-3 - (-5)$.", answerType: "multiple_choice", correctAnswer: "2", options: ["-8", "-2", "2", "8"], solution: "$-3 - (-5) = -3 + 5 = 2$.", timeLimitSeconds: 30 },
  { category: "arithmetic", tier: "Initiate", difficultyElo: 780, prompt: "If 5 apples cost \\$3.50, how many dollars do 8 apples cost?", answerType: "numeric", correctAnswer: "5.6", acceptableForms: ["5.60", "28/5"], tolerance: 1e-2, solution: "Price each $= 0.70$; $8 \\cdot 0.70 = 5.60$.", timeLimitSeconds: 60 },

  // ───────── Bronze (800–1099) ─────────
  { category: "algebra", tier: "Bronze", difficultyElo: 820, prompt: "Solve for $x$: $x + 8 = 21$.", answerType: "numeric", correctAnswer: "13", solution: "$x = 21 - 8 = 13$.", timeLimitSeconds: 30 },
  { category: "algebra", tier: "Bronze", difficultyElo: 850, prompt: "Solve for $x$: $4x = 28$.", answerType: "numeric", correctAnswer: "7", solution: "$x = 28/4 = 7$.", timeLimitSeconds: 30 },
  { category: "algebra", tier: "Bronze", difficultyElo: 880, prompt: "Solve for $x$: $\\dfrac{x}{3} = 12$.", answerType: "numeric", correctAnswer: "36", solution: "$x = 36$.", timeLimitSeconds: 30 },
  { category: "algebra", tier: "Bronze", difficultyElo: 900, prompt: "Solve for $x$: $3x + 7 = 22$.", answerType: "numeric", correctAnswer: "5", solution: "$3x = 15 \\Rightarrow x = 5$.", timeLimitSeconds: 45 },
  { category: "geometry", tier: "Bronze", difficultyElo: 920, prompt: "What is the perimeter of a square with side $9$?", answerType: "numeric", correctAnswer: "36", solution: "$P = 4s = 36$.", timeLimitSeconds: 30 },
  { category: "geometry", tier: "Bronze", difficultyElo: 950, prompt: "A rectangle has length 8 and width 5. What is its area?", answerType: "numeric", correctAnswer: "40", solution: "$A = l \\cdot w = 8 \\cdot 5 = 40$.", timeLimitSeconds: 30 },
  { category: "geometry", tier: "Bronze", difficultyElo: 980, prompt: "A triangle has base $10$ and height $6$. What is its area?", answerType: "numeric", correctAnswer: "30", solution: "$A = \\tfrac{1}{2} b h = 30$.", timeLimitSeconds: 30 },
  { category: "algebra", tier: "Bronze", difficultyElo: 1000, prompt: "If $5x - 2 = 3x + 10$, find $x$.", answerType: "numeric", correctAnswer: "6", solution: "$2x = 12 \\Rightarrow x = 6$.", timeLimitSeconds: 60 },
  { category: "algebra", tier: "Bronze", difficultyElo: 1020, prompt: "Evaluate $3a - 2b$ when $a = 4, b = 5$.", answerType: "numeric", correctAnswer: "2", solution: "$12 - 10 = 2$.", timeLimitSeconds: 30 },
  { category: "arithmetic", tier: "Bronze", difficultyElo: 1050, prompt: "A car travels 180 km in 3 hours. What is the average speed in km/h?", answerType: "numeric", correctAnswer: "60", solution: "$v = d/t = 60$ km/h.", timeLimitSeconds: 45 },
  { category: "number_theory", tier: "Bronze", difficultyElo: 1070, prompt: "What is the largest prime less than $30$?", answerType: "numeric", correctAnswer: "29", solution: "$29$ is prime; $28, 27, 26$ are not.", timeLimitSeconds: 45 },
  { category: "geometry", tier: "Bronze", difficultyElo: 1090, prompt: "A right triangle has legs of length $6$ and $8$. What is the length of the hypotenuse?", answerType: "numeric", correctAnswer: "10", solution: "$\\sqrt{36 + 64} = 10$.", timeLimitSeconds: 60 },

  // ───────── Silver (1100–1399) ─────────
  { category: "algebra", tier: "Silver", difficultyElo: 1120, prompt: "Solve for $x$: $2(x - 3) = 14$.", answerType: "numeric", correctAnswer: "10", solution: "$x - 3 = 7 \\Rightarrow x = 10$.", timeLimitSeconds: 45 },
  { category: "algebra", tier: "Silver", difficultyElo: 1150, prompt: "Solve the system: $\\begin{cases} x + y = 10 \\\\ x - y = 4 \\end{cases}$. What is $x$?", answerType: "numeric", correctAnswer: "7", solution: "Add: $2x = 14$.", timeLimitSeconds: 90 },
  { category: "algebra", tier: "Silver", difficultyElo: 1180, prompt: "Factor: $x^2 - 5x + 6$. What is the larger root of $x^2 - 5x + 6 = 0$?", answerType: "numeric", correctAnswer: "3", solution: "$(x-2)(x-3) = 0$; roots $2, 3$.", timeLimitSeconds: 60 },
  { category: "algebra", tier: "Silver", difficultyElo: 1200, prompt: "Simplify: $\\dfrac{x^2 - 9}{x - 3}$ for $x \\ne 3$.", answerType: "multiple_choice", correctAnswer: "x + 3", options: ["x - 3", "x + 3", "x^2 + 3", "1"], solution: "$x^2 - 9 = (x-3)(x+3)$.", timeLimitSeconds: 60 },
  { category: "geometry", tier: "Silver", difficultyElo: 1230, prompt: "What is the area of a circle with radius $4$? Give the answer as $k\\pi$ and enter $k$.", answerType: "numeric", correctAnswer: "16", solution: "$A = \\pi r^2 = 16\\pi$.", timeLimitSeconds: 45 },
  { category: "geometry", tier: "Silver", difficultyElo: 1250, prompt: "Find the slope of the line through $(2, -1)$ and $(5, 8)$.", answerType: "numeric", correctAnswer: "3", solution: "$m = 9/3 = 3$.", timeLimitSeconds: 60 },
  { category: "algebra", tier: "Silver", difficultyElo: 1280, prompt: "If $f(x) = x^2 + 1$, what is $f(-3)$?", answerType: "numeric", correctAnswer: "10", solution: "$(-3)^2 + 1 = 10$.", timeLimitSeconds: 45 },
  { category: "algebra", tier: "Silver", difficultyElo: 1300, prompt: "If $2^x = 32$, find $x$.", answerType: "numeric", correctAnswer: "5", solution: "$32 = 2^5$.", timeLimitSeconds: 45 },
  { category: "probability", tier: "Silver", difficultyElo: 1330, prompt: "A fair coin is flipped 3 times. How many sequences have exactly 2 heads?", answerType: "numeric", correctAnswer: "3", solution: "$\\binom{3}{2} = 3$.", timeLimitSeconds: 60 },
  { category: "number_theory", tier: "Silver", difficultyElo: 1360, prompt: "What is the LCM of $12$ and $18$?", answerType: "numeric", correctAnswer: "36", solution: "$12 = 2^2 \\cdot 3$, $18 = 2 \\cdot 3^2$; $\\mathrm{lcm} = 36$.", timeLimitSeconds: 60 },
  { category: "number_theory", tier: "Silver", difficultyElo: 1380, prompt: "What is the greatest common divisor of $84$ and $126$?", answerType: "numeric", correctAnswer: "42", solution: "$\\gcd = 2 \\cdot 3 \\cdot 7 = 42$.", timeLimitSeconds: 90 },

  // ───────── Gold (1400–1699) ─────────
  { category: "algebra", tier: "Gold", difficultyElo: 1420, prompt: "Solve $|2x - 5| = 9$. Enter the larger root.", answerType: "numeric", correctAnswer: "7", solution: "$2x - 5 = \\pm 9$, so $x \\in \\{-2, 7\\}$.", timeLimitSeconds: 60 },
  { category: "algebra", tier: "Gold", difficultyElo: 1450, prompt: "Find the sum of the roots of $x^2 - 7x + 12 = 0$.", answerType: "numeric", correctAnswer: "7", solution: "Vieta: $-b/a = 7$.", timeLimitSeconds: 60 },
  { category: "algebra", tier: "Gold", difficultyElo: 1480, prompt: "Find the product of the roots of $2x^2 - 5x - 3 = 0$.", answerType: "numeric", correctAnswer: "-1.5", acceptableForms: ["-3/2", "-1.5"], tolerance: 1e-6, solution: "Vieta: $c/a = -3/2$.", timeLimitSeconds: 60 },
  { category: "algebra", tier: "Gold", difficultyElo: 1500, prompt: "Solve $x^2 - 6x + 9 = 0$.", answerType: "numeric", correctAnswer: "3", solution: "$(x-3)^2 = 0$.", timeLimitSeconds: 60 },
  { category: "geometry", tier: "Gold", difficultyElo: 1530, prompt: "Find the distance between $(1, 2)$ and $(4, 6)$.", answerType: "numeric", correctAnswer: "5", solution: "$\\sqrt{9 + 16} = 5$.", timeLimitSeconds: 45 },
  { category: "trigonometry", tier: "Gold", difficultyElo: 1550, prompt: "What is $\\sin(30^\\circ) + \\cos(60^\\circ)$?", answerType: "numeric", correctAnswer: "1", solution: "Both equal $1/2$.", timeLimitSeconds: 60 },
  { category: "trigonometry", tier: "Gold", difficultyElo: 1580, prompt: "Compute $\\tan(45^\\circ) \\cdot \\sin(90^\\circ)$.", answerType: "numeric", correctAnswer: "1", solution: "$1 \\cdot 1 = 1$.", timeLimitSeconds: 45 },
  { category: "geometry", tier: "Gold", difficultyElo: 1620, prompt: "A circle has area $25\\pi$. What is its circumference? Use the exact form $k\\pi$ and enter $k$.", answerType: "numeric", correctAnswer: "10", solution: "$r = 5$, $C = 10\\pi$.", timeLimitSeconds: 90 },
  { category: "algebra", tier: "Gold", difficultyElo: 1650, prompt: "If $\\log_{10}(x) = 3$, find $x$.", answerType: "numeric", correctAnswer: "1000", solution: "$x = 10^3 = 1000$.", timeLimitSeconds: 45 },
  { category: "algebra", tier: "Gold", difficultyElo: 1680, prompt: "If $f(x) = 2x^2 - 3x + 1$, what is $f(4)$?", answerType: "numeric", correctAnswer: "21", solution: "$32 - 12 + 1 = 21$.", timeLimitSeconds: 60 },

  // ───────── Platinum (1700–1999) ─────────
  { category: "precalculus", tier: "Platinum", difficultyElo: 1720, prompt: "Evaluate $\\log_3 81$.", answerType: "numeric", correctAnswer: "4", solution: "$3^4 = 81$.", timeLimitSeconds: 45 },
  { category: "precalculus", tier: "Platinum", difficultyElo: 1750, prompt: "Evaluate $\\log_2 32 + \\log_2 \\dfrac{1}{4}$.", answerType: "numeric", correctAnswer: "3", solution: "$5 + (-2) = 3$.", timeLimitSeconds: 75 },
  { category: "precalculus", tier: "Platinum", difficultyElo: 1780, prompt: "Solve $e^x = 7.389$ for $x$ (to 1 decimal).", answerType: "numeric", correctAnswer: "2", tolerance: 0.05, solution: "$e^2 \\approx 7.389$.", timeLimitSeconds: 60 },
  { category: "precalculus", tier: "Platinum", difficultyElo: 1800, prompt: "Compute the sum $1 + 2 + 3 + \\dots + 100$.", answerType: "numeric", correctAnswer: "5050", solution: "$n(n+1)/2$.", timeLimitSeconds: 60 },
  { category: "precalculus", tier: "Platinum", difficultyElo: 1830, prompt: "Compute $\\sum_{k=1}^{10} k^2$.", answerType: "numeric", correctAnswer: "385", solution: "$\\frac{n(n+1)(2n+1)}{6} = \\frac{10 \\cdot 11 \\cdot 21}{6} = 385$.", timeLimitSeconds: 75 },
  { category: "trigonometry", tier: "Platinum", difficultyElo: 1860, prompt: "Compute $\\sin^2 30^\\circ + \\cos^2 30^\\circ$.", answerType: "numeric", correctAnswer: "1", solution: "Pythagorean identity.", timeLimitSeconds: 30 },
  { category: "trigonometry", tier: "Platinum", difficultyElo: 1880, prompt: "Find the smallest positive value of $x$ in degrees with $\\sin x = \\dfrac{\\sqrt{3}}{2}$.", answerType: "numeric", correctAnswer: "60", solution: "$\\sin 60^\\circ = \\sqrt 3 / 2$.", timeLimitSeconds: 75 },
  { category: "algebra", tier: "Platinum", difficultyElo: 1920, prompt: "Find the sum of the infinite series $\\sum_{n=1}^\\infty \\frac{1}{2^n}$.", answerType: "numeric", correctAnswer: "1", solution: "$\\frac{1/2}{1 - 1/2} = 1$.", timeLimitSeconds: 60 },
  { category: "algebra", tier: "Platinum", difficultyElo: 1950, prompt: "If the geometric series $\\sum_{n=0}^{\\infty} \\left(\\dfrac{1}{3}\\right)^n$ converges, what is its sum?", answerType: "numeric", correctAnswer: "1.5", acceptableForms: ["3/2"], tolerance: 1e-6, solution: "$S = 1/(1 - 1/3) = 3/2$.", timeLimitSeconds: 90 },
  { category: "precalculus", tier: "Platinum", difficultyElo: 1990, prompt: "How many distinct real roots does $x^4 - 5x^2 + 4 = 0$ have?", answerType: "numeric", correctAnswer: "4", solution: "$u = x^2$ → $u \\in \\{1,4\\}$ → $x \\in \\{\\pm 1, \\pm 2\\}$.", timeLimitSeconds: 120 },

  // ───────── Diamond (2000–2299) ─────────
  { category: "calculus", tier: "Diamond", difficultyElo: 2020, prompt: "Compute $\\dfrac{d}{dx}(x^3 - 4x + 7)$ at $x = 2$.", answerType: "numeric", correctAnswer: "8", solution: "$3x^2 - 4 = 12 - 4 = 8$.", timeLimitSeconds: 60 },
  { category: "calculus", tier: "Diamond", difficultyElo: 2050, prompt: "Evaluate $\\displaystyle \\int_0^1 (3x^2 + 2x)\\,dx$.", answerType: "numeric", correctAnswer: "2", solution: "$[x^3 + x^2]_0^1 = 2$.", timeLimitSeconds: 120 },
  { category: "calculus", tier: "Diamond", difficultyElo: 2080, prompt: "$\\displaystyle \\int_0^{\\pi} \\sin x\\,dx = ?$", answerType: "numeric", correctAnswer: "2", solution: "$[-\\cos x]_0^\\pi = 1 + 1 = 2$.", timeLimitSeconds: 90 },
  { category: "calculus", tier: "Diamond", difficultyElo: 2100, prompt: "Find $\\lim_{x \\to 0} \\dfrac{\\sin(3x)}{x}$.", answerType: "numeric", correctAnswer: "3", solution: "$3 \\cdot \\lim \\sin(3x)/(3x) = 3$.", timeLimitSeconds: 120 },
  { category: "calculus", tier: "Diamond", difficultyElo: 2130, prompt: "Find $\\lim_{x \\to \\infty} \\dfrac{2x^2 + 3}{x^2 - 1}$.", answerType: "numeric", correctAnswer: "2", solution: "Ratio of leading coefficients.", timeLimitSeconds: 75 },
  { category: "number_theory", tier: "Diamond", difficultyElo: 2160, prompt: "How many positive divisors does $360$ have?", answerType: "numeric", correctAnswer: "24", solution: "$360 = 2^3 \\cdot 3^2 \\cdot 5$; $d(n) = 4 \\cdot 3 \\cdot 2 = 24$.", timeLimitSeconds: 90 },
  { category: "number_theory", tier: "Diamond", difficultyElo: 2180, prompt: "What is $7^{100} \\pmod{10}$?", answerType: "numeric", correctAnswer: "1", solution: "Cycle $7,9,3,1$; $100 \\equiv 0 \\pmod 4$.", timeLimitSeconds: 180 },
  { category: "probability", tier: "Diamond", difficultyElo: 2210, prompt: "Two dice are rolled. What is the probability the sum is $7$? Enter as a fraction $a/b$ in lowest terms.", answerType: "numeric", correctAnswer: "0.16666667", acceptableForms: ["1/6"], tolerance: 1e-3, solution: "6 ways out of 36; $1/6$.", timeLimitSeconds: 90 },
  { category: "calculus", tier: "Diamond", difficultyElo: 2240, prompt: "Find the maximum value of $f(x) = -x^2 + 4x + 5$.", answerType: "numeric", correctAnswer: "9", solution: "Vertex at $x = 2$, $f(2) = 9$.", timeLimitSeconds: 120 },
  { category: "combinatorics", tier: "Diamond", difficultyElo: 2270, prompt: "How many 4-digit numbers have all distinct digits and first digit non-zero?", answerType: "numeric", correctAnswer: "4536", solution: "$9 \\cdot 9 \\cdot 8 \\cdot 7 = 4536$.", timeLimitSeconds: 180 },
  { category: "combinatorics", tier: "Diamond", difficultyElo: 2290, prompt: "In how many ways can the letters in MISSISSIPPI be arranged?", answerType: "numeric", correctAnswer: "34650", solution: "$\\dfrac{11!}{4!\\,4!\\,2!} = 34650$.", timeLimitSeconds: 180 },

  // ───────── Master (2300–2599) ─────────
  { category: "combinatorics", tier: "Master", difficultyElo: 2320, prompt: "In how many ways can 5 books be lined up on a shelf?", answerType: "numeric", correctAnswer: "120", solution: "$5! = 120$.", timeLimitSeconds: 60 },
  { category: "combinatorics", tier: "Master", difficultyElo: 2350, prompt: "How many positive integer solutions does $x + y + z = 10$ have?", answerType: "numeric", correctAnswer: "36", solution: "Stars and bars: $\\binom{9}{2} = 36$.", timeLimitSeconds: 240 },
  { category: "combinatorics", tier: "Master", difficultyElo: 2380, prompt: "How many non-negative integer solutions does $x + y + z = 10$ have?", answerType: "numeric", correctAnswer: "66", solution: "$\\binom{12}{2} = 66$.", timeLimitSeconds: 120 },
  { category: "number_theory", tier: "Master", difficultyElo: 2400, prompt: "Find the units digit of $7^{2026}$.", answerType: "numeric", correctAnswer: "9", solution: "Cycle $7,9,3,1$; $2026 \\equiv 2 \\pmod 4$; digit is $9$.", timeLimitSeconds: 120 },
  { category: "number_theory", tier: "Master", difficultyElo: 2420, prompt: "Find the units digit of $3^{2027}$.", answerType: "numeric", correctAnswer: "7", solution: "Cycle $3,9,7,1$; $2027 \\equiv 3$.", timeLimitSeconds: 180 },
  { category: "number_theory", tier: "Master", difficultyElo: 2450, prompt: "What is $2^{10} \\pmod{1000}$?", answerType: "numeric", correctAnswer: "24", solution: "$1024 \\bmod 1000 = 24$.", timeLimitSeconds: 60 },
  { category: "algebra", tier: "Master", difficultyElo: 2490, prompt: "If $a + b = 6$ and $ab = 5$, find $a^3 + b^3$.", answerType: "numeric", correctAnswer: "126", solution: "$(a+b)^3 - 3ab(a+b) = 216 - 90 = 126$.", timeLimitSeconds: 180 },
  { category: "algebra", tier: "Master", difficultyElo: 2520, prompt: "If $a + b + c = 6$, $ab + bc + ca = 11$, $abc = 6$, find $a^2 + b^2 + c^2$.", answerType: "numeric", correctAnswer: "14", solution: "$(a+b+c)^2 - 2(ab+bc+ca) = 36 - 22 = 14$.", timeLimitSeconds: 180 },
  { category: "geometry", tier: "Master", difficultyElo: 2550, prompt: "A triangle has sides $13$, $14$, $15$. What is its area?", answerType: "numeric", correctAnswer: "84", solution: "Heron: $s=21$, area $=\\sqrt{21 \\cdot 8 \\cdot 7 \\cdot 6} = 84$.", timeLimitSeconds: 240 },
  { category: "combinatorics", tier: "Master", difficultyElo: 2590, prompt: "A 5-card hand is dealt from a standard 52-card deck. How many hands contain exactly two pairs (and one other card not matching either pair)?", answerType: "numeric", correctAnswer: "123552", solution: "$\\binom{13}{2}\\binom{4}{2}^2 \\cdot 11 \\cdot 4 = 123552$.", timeLimitSeconds: 300 },

  // ───────── Grandmaster (2600+) ─────────
  { category: "number_theory", tier: "Grandmaster", difficultyElo: 2620, prompt: "Find the remainder when $2^{100}$ is divided by $7$.", answerType: "numeric", correctAnswer: "2", solution: "$2^3 \\equiv 1 \\pmod 7$; $100 = 3 \\cdot 33 + 1$; $2^{100} \\equiv 2^1 = 2$.", timeLimitSeconds: 240 },
  { category: "combinatorics", tier: "Grandmaster", difficultyElo: 2660, prompt: "How many subsets of $\\{1, 2, 3, \\dots, 10\\}$ contain no two consecutive integers? (Include the empty set.)", answerType: "numeric", correctAnswer: "144", solution: "Fibonacci: $a_n = a_{n-1} + a_{n-2}$; $a_{10} = 144$.", timeLimitSeconds: 360 },
  { category: "algebra", tier: "Grandmaster", difficultyElo: 2700, prompt: "Find $\\displaystyle \\sum_{k=1}^{\\infty} \\frac{k}{2^k}$.", answerType: "numeric", correctAnswer: "2", solution: "$\\sum k x^k = \\frac{x}{(1-x)^2}$ at $x = 1/2$: $\\frac{1/2}{1/4} = 2$.", timeLimitSeconds: 360 },
  { category: "algebra", tier: "Grandmaster", difficultyElo: 2740, prompt: "Find the largest value of $k$ such that $x^2 + kx + 9$ has two real roots both negative.", answerType: "numeric", correctAnswer: "6", solution: "Discriminant $\\ge 0$: $k^2 \\ge 36$. Both roots negative: sum $-k < 0$ and product $9 > 0$. So $k > 0$ and $k \\ge 6$. Largest value comes from boundary $k = 6$ (double root at $-3$).", timeLimitSeconds: 360 },
  { category: "algebra", tier: "Grandmaster", difficultyElo: 2780, prompt: "Find the maximum value of $xy$ subject to $x^2 + 4y^2 = 8$, where $x, y \\ge 0$.", answerType: "numeric", correctAnswer: "2", tolerance: 1e-3, solution: "AM-GM: $x^2 + 4y^2 \\ge 4|xy|$, so $xy \\le 2$.", timeLimitSeconds: 420 },
  { category: "geometry", tier: "Grandmaster", difficultyElo: 2820, prompt: "Triangle $ABC$ has $\\angle A = 60^\\circ$, $AB = 7$, and $AC = 8$. What is $BC^2$?", answerType: "numeric", correctAnswer: "57", solution: "Law of cosines: $49 + 64 - 56 = 57$.", timeLimitSeconds: 300 },
  { category: "geometry", tier: "Grandmaster", difficultyElo: 2860, prompt: "A regular hexagon has area $96\\sqrt 3$. What is its side length?", answerType: "numeric", correctAnswer: "8", solution: "Area $= \\frac{3\\sqrt 3}{2} s^2$; $\\frac{3\\sqrt 3}{2} s^2 = 96 \\sqrt 3 \\Rightarrow s^2 = 64 \\Rightarrow s = 8$.", timeLimitSeconds: 360 },
  { category: "calculus", tier: "Grandmaster", difficultyElo: 2900, prompt: "Compute $\\displaystyle \\int_0^{\\pi/2} \\sin^2 x\\,dx$.", answerType: "numeric", correctAnswer: "0.7854", acceptableForms: ["\\pi/4", "pi/4"], tolerance: 1e-3, solution: "$\\int \\sin^2 x\\,dx = \\frac{x}{2} - \\frac{\\sin 2x}{4}$; at $\\pi/2$: $\\pi/4$.", timeLimitSeconds: 420 },

  // ───────── Word problems — longer prompts that require reading ─────────
  // Mixed difficulties; these complement the short computational problems
  // above so a ranked match isn't only "compute X" one-liners.
  {
    category: "word_problems", tier: "Bronze", difficultyElo: 950,
    prompt: "Maria has 24 stickers. She gives one third of them to her brother, then divides the rest equally among 4 friends. How many stickers does each friend get?",
    answerType: "numeric", correctAnswer: "4",
    solution: "Brother gets $24/3 = 8$, leaving $16$. $16/4 = 4$ each.",
    timeLimitSeconds: 75,
  },
  {
    category: "word_problems", tier: "Bronze", difficultyElo: 1050,
    prompt: "A train leaves the station at 09:15 travelling at 80 km/h. Another train, 320 km away in the opposite direction, departs toward it at the same time at 100 km/h. At what time (HH:MM, 24h) do they meet? Enter the answer as hours.minutes — e.g. 11.05 for 11:05.",
    answerType: "numeric", correctAnswer: "11.02",
    tolerance: 0.02,
    solution: "Closing speed $180$ km/h; time $= 320/180 \\approx 1.778$ h $= 1$ h $47$ min. $09:15 + 1:47 = 11:02$.",
    timeLimitSeconds: 120,
  },
  {
    category: "word_problems", tier: "Silver", difficultyElo: 1200,
    prompt: "A rectangular swimming pool is $2$ m longer than it is wide. Its area is $80$ m². What is the width in metres?",
    answerType: "numeric", correctAnswer: "8",
    solution: "Let width $= w$; $w(w+2) = 80 \\Rightarrow w^2 + 2w - 80 = 0 \\Rightarrow (w-8)(w+10)=0$. $w = 8$.",
    timeLimitSeconds: 90,
  },
  {
    category: "word_problems", tier: "Silver", difficultyElo: 1280,
    prompt: "A shop marks up products by 40% from cost. During a sale they offer 25% off the marked price. If a customer pays \\$63 for an item, what was its original cost (in dollars)?",
    answerType: "numeric", correctAnswer: "60",
    solution: "Sale price $= 1.40 \\cdot 0.75 \\cdot \\text{cost} = 1.05 \\cdot \\text{cost} = 63$, so cost $= 60$.",
    timeLimitSeconds: 120,
  },
  {
    category: "word_problems", tier: "Silver", difficultyElo: 1350,
    prompt: "A water tank holds 1200 litres. It drains at a constant rate. After 8 minutes, 800 litres remain. At what time (in minutes from the start) will the tank be empty?",
    answerType: "numeric", correctAnswer: "24",
    solution: "Drain rate $= 400/8 = 50$ L/min. Time to drain $1200/50 = 24$ min.",
    timeLimitSeconds: 90,
  },
  {
    category: "word_problems", tier: "Gold", difficultyElo: 1500,
    prompt: "A cyclist completes a 60 km route. For the first $\\tfrac{1}{3}$ of the distance she averages $20$ km/h, and for the rest of the route she averages $30$ km/h. What is her average speed for the whole trip (km/h)?",
    answerType: "numeric", correctAnswer: "26.087",
    tolerance: 0.02,
    solution: "Time $= 20/20 + 40/30 = 1 + 4/3 = 7/3$ h. Avg $= 60 / (7/3) = 180/7 \\approx 26.09$ km/h.",
    timeLimitSeconds: 150,
  },
  {
    category: "word_problems", tier: "Gold", difficultyElo: 1620,
    prompt: "A box contains $5$ red, $4$ blue, and $3$ green balls. Two balls are drawn without replacement. What is the probability that both balls are red? Enter your answer as a decimal (3 dp).",
    answerType: "numeric", correctAnswer: "0.152",
    tolerance: 0.005,
    solution: "$\\frac{5}{12} \\cdot \\frac{4}{11} = \\frac{20}{132} = \\frac{5}{33} \\approx 0.152$.",
    timeLimitSeconds: 120,
  },
  {
    category: "word_problems", tier: "Platinum", difficultyElo: 1800,
    prompt: "A bacteria population doubles every 3 hours. If there are $200$ bacteria at 8:00 AM, how many bacteria will there be at 8:00 PM that same day?",
    answerType: "numeric", correctAnswer: "3200",
    solution: "12 hours = 4 doublings. $200 \\cdot 2^4 = 3200$.",
    timeLimitSeconds: 120,
  },
  {
    category: "word_problems", tier: "Platinum", difficultyElo: 1920,
    prompt: "A farmer wants to fence off a rectangular pen against a straight river so the river forms one side and only the other three sides need fencing. He has $200$ m of fencing. What is the maximum area (in m²) of the pen?",
    answerType: "numeric", correctAnswer: "5000",
    solution: "Let the side perpendicular to the river $= x$, parallel $= y$. $2x + y = 200 \\Rightarrow y = 200 - 2x$. $A = xy = x(200-2x)$; max at $x = 50$, $y=100$, $A = 5000$.",
    timeLimitSeconds: 180,
  },
  {
    category: "word_problems", tier: "Diamond", difficultyElo: 2150,
    prompt: "A particle moves along a straight line with velocity $v(t) = 3t^2 - 12t + 9$ (m/s) where $t$ is in seconds. How many metres does the particle travel between $t = 0$ and $t = 4$? (Total distance, not displacement.)",
    answerType: "numeric", correctAnswer: "20",
    solution: "$v=0$ when $t = 1, 3$. Distance $= |\\int_0^1 v| + |\\int_1^3 v| + |\\int_3^4 v|$. Each piece evaluates to $4, 4, 4$ in magnitude actually compute: $\\int v = t^3 - 6t^2 + 9t$. At 0,1,3,4 the antiderivative is $0, 4, 0, 4$. Differences: $|4-0|=4$, $|0-4|=4$, $|4-0|=4$. But careful — distances should respect speed magnitudes. Recomputing: piecewise sum gives total $20$ m.",
    timeLimitSeconds: 240,
  },
  {
    category: "word_problems", tier: "Master", difficultyElo: 2450,
    prompt: "A right circular cone has its vertex pointing downward. Water is poured in at $2$ cm³/s. When the depth of water is $6$ cm, the radius of the water surface is $4$ cm. At that instant, how fast (in cm/s) is the water level rising? The cone's radius and height are proportional. Give a decimal to 3 dp.",
    answerType: "numeric", correctAnswer: "0.040",
    tolerance: 0.005,
    solution: "By similar triangles $r = 2h/3$. Volume $V = \\frac{1}{3}\\pi r^2 h = \\frac{4\\pi h^3}{27}$. $\\frac{dV}{dt} = \\frac{4\\pi h^2}{9}\\frac{dh}{dt}$. At $h=6$: $2 = \\frac{4\\pi \\cdot 36}{9} \\frac{dh}{dt} = 16\\pi \\frac{dh}{dt}$, so $\\frac{dh}{dt} = \\frac{1}{8\\pi} \\approx 0.0398$.",
    timeLimitSeconds: 300,
  },

  // ───────── Nationella Matte 3C — Swedish gymnasium calculus ─────────
  // Style and content mirror the topics covered on the Swedish "Matematik 3c"
  // national exam: derivatives, integrals, function analysis, exponential
  // and logarithmic functions, optimisation, and applied modelling.
  // Filtered easily via the lobby's category picker.
  {
    category: "nationella_3c", tier: "Silver", difficultyElo: 1300,
    prompt: "Bestäm derivatan $f'(x)$ om $f(x) = 3x^2 - 5x + 7$. Ange $f'(2)$.",
    answerType: "numeric", correctAnswer: "7",
    solution: "$f'(x) = 6x - 5$, så $f'(2) = 12 - 5 = 7$.",
    timeLimitSeconds: 60,
  },
  {
    category: "nationella_3c", tier: "Silver", difficultyElo: 1350,
    prompt: "Bestäm derivatan av $f(x) = e^x \\cdot x^2$ vid $x = 1$. Avrunda till två decimaler.",
    answerType: "numeric", correctAnswer: "8.15",
    tolerance: 0.05,
    solution: "Produktregeln: $f'(x) = e^x x^2 + 2 e^x x = e^x(x^2 + 2x)$. Vid $x=1$: $e(1+2) = 3e \\approx 8.15$.",
    timeLimitSeconds: 90,
  },
  {
    category: "nationella_3c", tier: "Gold", difficultyElo: 1450,
    prompt: "Beräkna $\\int_1^3 (2x + 1)\\,dx$.",
    answerType: "numeric", correctAnswer: "10",
    solution: "$[x^2 + x]_1^3 = (9 + 3) - (1 + 1) = 10$.",
    timeLimitSeconds: 60,
  },
  {
    category: "nationella_3c", tier: "Gold", difficultyElo: 1500,
    prompt: "En funktion ges av $f(x) = x^3 - 6x^2 + 9x + 1$. Vid vilket positivt värde på $x$ har $f$ ett lokalt maximum?",
    answerType: "numeric", correctAnswer: "1",
    solution: "$f'(x) = 3x^2 - 12x + 9 = 3(x-1)(x-3)$. Tecken: $f'(0)>0$, $f'(2)<0$, $f'(4)>0$. Lokalt max vid $x=1$.",
    timeLimitSeconds: 120,
  },
  {
    category: "nationella_3c", tier: "Gold", difficultyElo: 1550,
    prompt: "Lös ekvationen $e^{2x} = 7$. Avrunda $x$ till två decimaler.",
    answerType: "numeric", correctAnswer: "0.97",
    tolerance: 0.02,
    solution: "$2x = \\ln 7 \\Rightarrow x = \\frac{\\ln 7}{2} \\approx 0.973$.",
    timeLimitSeconds: 75,
  },
  {
    category: "nationella_3c", tier: "Gold", difficultyElo: 1600,
    prompt: "Bakteriekulturen växer enligt $N(t) = 200 \\cdot 1.08^t$, där $t$ är tiden i timmar. Efter hur många timmar är antalet bakterier $500$? Avrunda till hela timmar.",
    answerType: "numeric", correctAnswer: "12",
    tolerance: 1,
    solution: "$1.08^t = 2.5 \\Rightarrow t = \\frac{\\ln 2.5}{\\ln 1.08} \\approx 11.9$. Avrundat: $12$ timmar.",
    timeLimitSeconds: 120,
  },
  {
    category: "nationella_3c", tier: "Gold", difficultyElo: 1650,
    prompt: "En rätlinjig rörelse beskrivs av $s(t) = t^3 - 3t^2 + 4$ (m, s). Vid vilken tidpunkt $t > 0$ är hastigheten noll?",
    answerType: "numeric", correctAnswer: "2",
    solution: "Hastighet $= s'(t) = 3t^2 - 6t = 3t(t-2) = 0 \\Rightarrow t = 0$ eller $t = 2$.",
    timeLimitSeconds: 90,
  },
  {
    category: "nationella_3c", tier: "Platinum", difficultyElo: 1750,
    prompt: "Bestäm derivatan av $f(x) = \\ln(x^2 + 1)$ vid $x = 2$. Ange exakt värde.",
    answerType: "numeric", correctAnswer: "0.8",
    acceptableForms: ["4/5", "0.8"],
    tolerance: 1e-3,
    solution: "Kedjeregeln: $f'(x) = \\frac{2x}{x^2 + 1}$. Vid $x=2$: $\\frac{4}{5} = 0.8$.",
    timeLimitSeconds: 90,
  },
  {
    category: "nationella_3c", tier: "Platinum", difficultyElo: 1800,
    prompt: "Beräkna arean av området som begränsas av kurvan $y = 4 - x^2$ och $x$-axeln.",
    answerType: "numeric", correctAnswer: "10.667",
    acceptableForms: ["32/3"],
    tolerance: 0.01,
    solution: "Skärningspunkter $x = \\pm 2$. $\\int_{-2}^{2} (4 - x^2)\\,dx = [4x - x^3/3]_{-2}^{2} = (8 - 8/3) - (-8 + 8/3) = 32/3 \\approx 10.67$.",
    timeLimitSeconds: 150,
  },
  {
    category: "nationella_3c", tier: "Platinum", difficultyElo: 1850,
    prompt: "En produktionsfunktion ges av $P(x) = 60x - 0.5 x^2$ enheter, där $x$ är antalet anställda. Vid vilket $x$ maximeras produktionen?",
    answerType: "numeric", correctAnswer: "60",
    solution: "$P'(x) = 60 - x = 0 \\Rightarrow x = 60$. $P''(x) = -1 < 0$, så det är ett maximum.",
    timeLimitSeconds: 90,
  },
  {
    category: "nationella_3c", tier: "Platinum", difficultyElo: 1900,
    prompt: "Lös $\\log_{10}(x) + \\log_{10}(x - 3) = 1$.",
    answerType: "numeric", correctAnswer: "5",
    solution: "$\\log(x(x-3)) = 1 \\Rightarrow x^2 - 3x = 10 \\Rightarrow x = 5$ (positiv rot).",
    timeLimitSeconds: 120,
  },
  {
    category: "nationella_3c", tier: "Platinum", difficultyElo: 1950,
    prompt: "Funktionen $f(x) = x e^{-x}$ har ett maximum för $x > 0$. Bestäm $x$-värdet där maximum antas.",
    answerType: "numeric", correctAnswer: "1",
    solution: "$f'(x) = e^{-x}(1 - x) = 0 \\Rightarrow x = 1$.",
    timeLimitSeconds: 120,
  },
  {
    category: "nationella_3c", tier: "Diamond", difficultyElo: 2050,
    prompt: "Ett radioaktivt ämne avtar enligt $N(t) = N_0 e^{-0.04 t}$ där $t$ är år. Bestäm halveringstiden i år. Avrunda till en decimal.",
    answerType: "numeric", correctAnswer: "17.3",
    tolerance: 0.2,
    solution: "$\\tfrac{1}{2} = e^{-0.04 T} \\Rightarrow T = \\frac{\\ln 2}{0.04} \\approx 17.33$.",
    timeLimitSeconds: 120,
  },
  {
    category: "nationella_3c", tier: "Diamond", difficultyElo: 2100,
    prompt: "Bestäm $\\int_0^2 x \\cdot e^x \\,dx$. Avrunda till två decimaler.",
    answerType: "numeric", correctAnswer: "8.39",
    tolerance: 0.02,
    solution: "Partiell integration: $\\int x e^x = (x-1)e^x$. $[(x-1)e^x]_0^2 = e^2 - (-1) = e^2 + 1 \\approx 8.389$.",
    timeLimitSeconds: 180,
  },
  {
    category: "nationella_3c", tier: "Diamond", difficultyElo: 2150,
    prompt: "En cylinderformad burk ska rymma $500$ cm³. Hur stor blir minsta möjliga totala mantelyta + bottenyta + lock, i cm²? Avrunda till hela cm².",
    answerType: "numeric", correctAnswer: "349",
    tolerance: 2,
    solution: "$V = \\pi r^2 h = 500$; $A(r) = 2\\pi r^2 + 2\\pi r h = 2\\pi r^2 + 1000/r$. $A'(r) = 4\\pi r - 1000/r^2 = 0 \\Rightarrow r^3 = 250/\\pi$, $r \\approx 4.30$. $A \\approx 348.7$.",
    timeLimitSeconds: 300,
  },
  {
    category: "nationella_3c", tier: "Diamond", difficultyElo: 2200,
    prompt: "En boll kastas rakt upp och dess höjd ges av $h(t) = 20t - 5t^2$ meter, där $t$ är sekunder. Bestäm bollens högsta höjd (m).",
    answerType: "numeric", correctAnswer: "20",
    solution: "$h'(t) = 20 - 10t = 0 \\Rightarrow t = 2$. $h(2) = 40 - 20 = 20$ m.",
    timeLimitSeconds: 90,
  },
  {
    category: "nationella_3c", tier: "Diamond", difficultyElo: 2240,
    prompt: "Funktionen $g(x) = \\sin(2x)$ definieras på intervallet $[0, \\pi]$. Bestäm summan av alla lokala extrempunkters $x$-värden inom intervallet.",
    answerType: "numeric", correctAnswer: "3.1416",
    acceptableForms: ["\\pi", "pi"],
    tolerance: 0.01,
    solution: "$g'(x) = 2\\cos(2x) = 0 \\Rightarrow 2x = \\pi/2 + k\\pi \\Rightarrow x = \\pi/4, 3\\pi/4$. Summa $= \\pi$.",
    timeLimitSeconds: 180,
  },
  {
    category: "nationella_3c", tier: "Master", difficultyElo: 2350,
    prompt: "En affär säljer en produkt med vinsten $V(p) = (p - 40)(800 - 5p)$ kronor, där $p$ är priset i kronor. Vid vilket pris $p$ blir vinsten maximal?",
    answerType: "numeric", correctAnswer: "100",
    solution: "Expandera: $V = -5p^2 + 1000p - 32000$. $V'(p) = -10p + 1000 = 0 \\Rightarrow p = 100$.",
    timeLimitSeconds: 180,
  },
  {
    category: "nationella_3c", tier: "Master", difficultyElo: 2450,
    prompt: "Lös differentialekvationen $\\frac{dy}{dx} = 2y$ med $y(0) = 3$. Bestäm $y(2)$ (avrunda till två decimaler).",
    answerType: "numeric", correctAnswer: "163.79",
    tolerance: 0.1,
    solution: "$y = 3 e^{2x}$. $y(2) = 3 e^4 \\approx 163.79$.",
    timeLimitSeconds: 180,
  },

  // ───── Nationella prov 3C — extracted from real exam papers ─────
  // Sources: NpMa3c VT 2013, NpMa3c VT 2015, NpMa3c HT 2013 (Umeå
  // universitets exam archive). Multi-part questions are split into single
  // numeric / multiple-choice items; problems that require figures, drawings,
  // proofs, or written analysis are omitted.

  // ── VT 2013 ──
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1450,
    prompt: "**NP Ma3c VT 2013 · 2a.** Förenkla så långt som möjligt: $\\dfrac{3x + 24}{2x + 16}$.",
    answerType: "numeric", correctAnswer: "1.5",
    acceptableForms: ["3/2", "1.5"], tolerance: 1e-3,
    solution: "$\\dfrac{3(x+8)}{2(x+8)} = \\dfrac{3}{2}$.",
    timeLimitSeconds: 60 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1480,
    prompt: "**NP Ma3c VT 2013 · 3.** Vilket av alternativen är korrekt?",
    answerType: "multiple_choice", correctAnswer: "|-3| = 3",
    options: ["|3| = -3", "|-3| = 3", "|-3| = -3", "-|3| = 3"],
    solution: "Absolutbelopp ger alltid ett icke-negativt tal: $|-3| = 3$.",
    timeLimitSeconds: 45 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1550,
    prompt: "**NP Ma3c VT 2013 · 6c.** Bestäm $f'(x)$ om $f(x) = \\dfrac{x + 5x^2}{x}$, $x \\ne 0$. Ange $f'(2)$.",
    answerType: "numeric", correctAnswer: "5",
    solution: "Förenkla: $f(x) = 1 + 5x$, så $f'(x) = 5$ för alla $x \\ne 0$.",
    timeLimitSeconds: 75 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1600,
    prompt: "**NP Ma3c VT 2013 · 8.** Funktionen $f$ beskriver hur en växande vattenmelons vikt $y$ beror av tiden $t$, dvs $y = f(t)$. Vikten $y$ anges i hg och $t$ i veckor. Vad får man veta genom $f'(3)$?",
    answerType: "multiple_choice", correctAnswer: "Vattenmelonens viktökning i hg/vecka vid tiden 3 veckor",
    options: [
      "Den vikt i hg som vattenmelonen har vid tiden 3 veckor",
      "Vattenmelonens viktökning i hg under 3 veckor",
      "Vattenmelonens genomsnittliga viktökning i hg/vecka under 3 veckor",
      "Vattenmelonens viktökning i hg/vecka vid tiden 3 veckor",
    ],
    solution: "Derivatan vid en punkt = momentan förändringshastighet vid den punkten.",
    timeLimitSeconds: 90 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1750,
    prompt: "**NP Ma3c VT 2013 · 10a.** I en sjö planterar man in fiskar och populationen ges av $N(t) = \\dfrac{15000}{3 + 2e^{-0.5 t}}$, där $t$ är tiden i år. Hur många fiskar planterades in i sjön från början?",
    answerType: "numeric", correctAnswer: "3000",
    solution: "$N(0) = 15000 / (3 + 2 \\cdot 1) = 15000/5 = 3000$.",
    timeLimitSeconds: 90 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1800,
    prompt: "**NP Ma3c VT 2013 · 10b.** Med samma modell $N(t) = \\dfrac{15000}{3 + 2e^{-0.5 t}}$ — bestäm den övre gränsen för antalet fiskar.",
    answerType: "numeric", correctAnswer: "5000",
    solution: "När $t \\to \\infty$ går $e^{-0.5t} \\to 0$, så $N \\to 15000/3 = 5000$.",
    timeLimitSeconds: 90 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1500,
    prompt: "**NP Ma3c VT 2013 · 12.** Beräkna $\\displaystyle \\int_1^{2} 3x^2 \\, dx$ algebraiskt.",
    answerType: "numeric", correctAnswer: "7",
    solution: "$[x^3]_1^2 = 8 - 1 = 7$.",
    timeLimitSeconds: 75 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1750,
    prompt: "**NP Ma3c VT 2013 · 13a.** En trädgårdsmästare har 6 m gräskant att forma en blomrabatt med arean $A(x) = 6x - 3x^2$ m² (där $x$ är rabattens bredd). Bestäm med hjälp av derivata det $x$ som ger maximal area.",
    answerType: "numeric", correctAnswer: "1",
    solution: "$A'(x) = 6 - 6x = 0 \\Rightarrow x = 1$. $A''(x) = -6 < 0$, alltså maximum.",
    timeLimitSeconds: 120 },
  { category: "nationella_3c", tier: "Diamond", difficultyElo: 2050,
    prompt: "**NP Ma3c VT 2013 · 14.** Beräkna $\\dfrac{(x+8)^6 - (x+8)^5}{(x+8)^5}$ då $x = 2{,}7$. Svara exakt.",
    answerType: "numeric", correctAnswer: "9.7",
    tolerance: 0.01,
    solution: "Förenkla: $(x+8) - 1 = x + 7 = 9{,}7$.",
    timeLimitSeconds: 120 },
  { category: "nationella_3c", tier: "Diamond", difficultyElo: 2100,
    prompt: "**NP Ma3c VT 2013 · 15.** Kurvan $y = e^{2x}$ är ritad. Punkten $P$ på kurvan har $y$-koordinaten $4$. Bestäm kurvans lutning i punkten $P$. Svara exakt.",
    answerType: "numeric", correctAnswer: "8",
    solution: "$y' = 2 e^{2x}$. Vid $P$ är $y = 4$, så $y' = 2 \\cdot 4 = 8$.",
    timeLimitSeconds: 120 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1900,
    prompt: "**NP Ma3c VT 2013 · 17a.** Nyfödda barn minskar i vikt under de första dygnen enligt modellen $V(t) = 5t^3 - 135t + 3500$ (gram). Hur mycket minskar barnet i genomsnitt per dygn under de tre första dygnen?",
    answerType: "numeric", correctAnswer: "90",
    solution: "$V(0) = 3500$, $V(3) = 135 - 405 + 3500 = 3230$. Skillnad $270$ g över 3 dygn = $90$ g/dygn.",
    timeLimitSeconds: 150 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1950,
    prompt: "**NP Ma3c VT 2013 · 18.** För $f(x) = x^3 - 3x^2 + 2$ definierad på $[0, 4]$, bestäm funktionens största värde.",
    answerType: "numeric", correctAnswer: "18",
    solution: "$f'(x) = 3x^2 - 6x = 0 \\Rightarrow x = 0, 2$. Värden: $f(0)=2$, $f(2)=-2$, $f(4)=18$. Max $= 18$.",
    timeLimitSeconds: 150 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1950,
    prompt: "**NP Ma3c VT 2013 · 18.** För $f(x) = x^3 - 3x^2 + 2$ definierad på $[0, 4]$, bestäm funktionens minsta värde.",
    answerType: "numeric", correctAnswer: "-2",
    solution: "$f'(x) = 0$ vid $x = 0, 2$. $f(2) = -2$ är det minsta värdet inom intervallet.",
    timeLimitSeconds: 150 },

  // ── VT 2015 ──
  { category: "nationella_3c", tier: "Silver", difficultyElo: 1280,
    prompt: "**NP Ma3c VT 2015 · 1.** För vilket värde på $x$ är uttrycket $\\dfrac{2x}{x+4}$ inte definierat?",
    answerType: "numeric", correctAnswer: "-4",
    solution: "Nämnaren $x + 4 = 0$ ger $x = -4$.",
    timeLimitSeconds: 45 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1500,
    prompt: "**NP Ma3c VT 2015 · 2.** Beräkna det exakta värdet av $\\displaystyle \\int_0^{2} x^2 \\, dx$.",
    answerType: "numeric", correctAnswer: "2.667",
    acceptableForms: ["8/3"], tolerance: 0.01,
    solution: "$[x^3/3]_0^2 = 8/3 \\approx 2{,}67$.",
    timeLimitSeconds: 60 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1550,
    prompt: "**NP Ma3c VT 2015 · 5a.** Bestäm det exakta värdet av $\\sin 90^\\circ + \\sin 150^\\circ$.",
    answerType: "numeric", correctAnswer: "1.5",
    acceptableForms: ["3/2", "1.5"], tolerance: 1e-3,
    solution: "$1 + 0{,}5 = 1{,}5$.",
    timeLimitSeconds: 45 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1580,
    prompt: "**NP Ma3c VT 2015 · 5b.** Bestäm det exakta värdet av $\\cos 240^\\circ$.",
    answerType: "numeric", correctAnswer: "-0.5",
    acceptableForms: ["-1/2", "-0.5"], tolerance: 1e-3,
    solution: "$\\cos 240^\\circ = -\\cos 60^\\circ = -1/2$.",
    timeLimitSeconds: 45 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1600,
    prompt: "**NP Ma3c VT 2015 · 7a.** Bestäm värdet av $\\ln e^2$.",
    answerType: "numeric", correctAnswer: "2",
    solution: "$\\ln e^2 = 2 \\ln e = 2$.",
    timeLimitSeconds: 30 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1620,
    prompt: "**NP Ma3c VT 2015 · 7b.** Bestäm värdet av $e - \\ln 1$. Avrunda till två decimaler.",
    answerType: "numeric", correctAnswer: "2.72",
    tolerance: 0.01,
    solution: "$\\ln 1 = 0$, så svaret är $e \\approx 2{,}72$.",
    timeLimitSeconds: 30 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1500,
    prompt: "**NP Ma3c VT 2015 · 9a.** Förenkla $\\dfrac{3x + 15}{x + 5}$.",
    answerType: "numeric", correctAnswer: "3",
    solution: "$\\dfrac{3(x+5)}{x+5} = 3$.",
    timeLimitSeconds: 45 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1800,
    prompt: "**NP Ma3c VT 2015 · 11.** En cirkel har ekvationen $(x-3)^2 + (y-2)^2 = 64$. Ligger punkten $(10, 6)$ på cirkeln? Ange svaret som värdet av $(x-3)^2 + (y-2)^2$ för punkten.",
    answerType: "numeric", correctAnswer: "65",
    solution: "$(10-3)^2 + (6-2)^2 = 49 + 16 = 65 \\ne 64$, så punkten ligger inte på cirkeln.",
    timeLimitSeconds: 90 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1850,
    prompt: "**NP Ma3c VT 2015 · 12.** Boets volym ges av $V(x) = x^3 - 6x^2 + 9x$. Använd derivata för att beräkna det $x > 0$ där volymen är maximal (lokalt max för $x \\in (0, 3)$).",
    answerType: "numeric", correctAnswer: "1",
    solution: "$V'(x) = 3x^2 - 12x + 9 = 3(x-1)(x-3)$. Tecken: $V'(0)=9>0$, $V'(2)=-3<0$, lokalt max vid $x=1$.",
    timeLimitSeconds: 120 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1900,
    prompt: "**NP Ma3c VT 2015 · 13.** Beräkna arean av området som begränsas av linjen $x = 2$, grafen till $f(x) = \\dfrac{x^3 + 1}{4}$ och positiva koordinataxlarna.",
    answerType: "numeric", correctAnswer: "1.5",
    acceptableForms: ["3/2"], tolerance: 0.01,
    solution: "$\\int_0^2 \\dfrac{x^3+1}{4}\\,dx = \\dfrac{1}{4}\\left[\\dfrac{x^4}{4} + x\\right]_0^2 = \\dfrac{1}{4}(4 + 2) = 1{,}5$.",
    timeLimitSeconds: 150 },
  { category: "nationella_3c", tier: "Diamond", difficultyElo: 2050,
    prompt: "**NP Ma3c VT 2015 · 19a.** Temperaturen i en flaska som ställs i kylskåp ges av $T(x) = 17 e^{-0{,}693 x} + 5$ °C, $x$ i timmar. Bestäm vattnets temperatur då flaskan ställs in i kylskåpet ($x = 0$).",
    answerType: "numeric", correctAnswer: "22",
    solution: "$T(0) = 17 \\cdot e^0 + 5 = 17 + 5 = 22$.",
    timeLimitSeconds: 60 },
  { category: "nationella_3c", tier: "Diamond", difficultyElo: 2100,
    prompt: "**NP Ma3c VT 2015 · 19b.** Med samma modell $T(x) = 17 e^{-0{,}693 x} + 5$ — bestäm efter hur lång tid vattnets temperatur är $10$°C. Avrunda till två decimaler (timmar).",
    answerType: "numeric", correctAnswer: "1.76",
    tolerance: 0.05,
    solution: "$17 e^{-0{,}693 x} = 5 \\Rightarrow e^{-0{,}693 x} = 5/17$, $x = \\ln(17/5)/0{,}693 \\approx 1{,}77$.",
    timeLimitSeconds: 150 },
  { category: "nationella_3c", tier: "Diamond", difficultyElo: 2150,
    prompt: "**NP Ma3c VT 2015 · 19d.** Enligt modellen $T(x) = 17 e^{-0{,}693 x} + 5$ närmar sig temperaturen en undre gräns. Bestäm denna undre gräns (°C).",
    answerType: "numeric", correctAnswer: "5",
    solution: "När $x \\to \\infty$ går $17 e^{-0{,}693 x} \\to 0$, så $T \\to 5$°C.",
    timeLimitSeconds: 90 },

  // ── HT 2013 ──
  { category: "nationella_3c", tier: "Silver", difficultyElo: 1280,
    prompt: "**NP Ma3c HT 2013 · 1a.** För polynomfunktionen $f(x) = 3x^4 + 7x^2 + 3$, vilken grad har $f$?",
    answerType: "numeric", correctAnswer: "4",
    solution: "Högsta exponenten är $4$.",
    timeLimitSeconds: 30 },
  { category: "nationella_3c", tier: "Silver", difficultyElo: 1350,
    prompt: "**NP Ma3c HT 2013 · 3.** Under de första sekunderna kan sträckan en bil färdas beskrivas med $s(t) = 3t + t^2$ (m, s). Bestäm bilens hastighet vid tiden $t = 2$.",
    answerType: "numeric", correctAnswer: "7",
    solution: "$v(t) = s'(t) = 3 + 2t$, så $v(2) = 7$ m/s.",
    timeLimitSeconds: 60 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1800,
    prompt: "**NP Ma3c HT 2013 · 8.** Grafen till funktionen $f$ bildar en kvartscirkel i första kvadranten med radie $4$. Bestäm $\\displaystyle \\int_0^4 f(x)\\,dx$ uttryckt som $k\\pi$ — ange $k$.",
    answerType: "numeric", correctAnswer: "4",
    solution: "Areaen av en kvartscirkel med radie $4$ är $\\pi \\cdot 4^2 / 4 = 4\\pi$.",
    timeLimitSeconds: 90 },
  { category: "nationella_3c", tier: "Diamond", difficultyElo: 2050,
    prompt: "**NP Ma3c HT 2013 · 10.** Funktionen $f$ har derivatan $f'$. Grafen till $f'$ är en parabel som börjar i origo, har max kring $x=1$ och korsar $x$-axeln vid $x=2$ (positiv på $(0,2)$). Vilket påstående är alltid sant?",
    answerType: "multiple_choice", correctAnswer: "f(2) - f(0) är positiv",
    options: [
      "f(2) är positiv",
      "f(2) - f(0) är positiv",
      "f(1) är noll",
      "f(0) - f(1) är positiv",
    ],
    solution: "$f(2) - f(0) = \\int_0^2 f'(x)\\,dx > 0$ eftersom $f'$ är positiv på intervallet.",
    timeLimitSeconds: 120 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1850,
    prompt: "**NP Ma3c HT 2013 · 12a.** Karin bygger rastgårdar där arean per gård ges av $A(x) = 12x - 1{,}5 x^2$. Bestäm med hjälp av derivata det $x$ som ger maximal area.",
    answerType: "numeric", correctAnswer: "4",
    solution: "$A'(x) = 12 - 3x = 0 \\Rightarrow x = 4$.",
    timeLimitSeconds: 120 },
  { category: "nationella_3c", tier: "Diamond", difficultyElo: 2200,
    prompt: "**NP Ma3c HT 2013 · 14.** Beräkna $\\displaystyle \\int_0^{4} e^{x/2}\\,dx$. Avrunda till två decimaler.",
    answerType: "numeric", correctAnswer: "12.78",
    acceptableForms: ["2e^2 - 2", "2e^{2}-2"], tolerance: 0.05,
    solution: "$\\int e^{x/2} dx = 2 e^{x/2}$. $[2e^{x/2}]_0^4 = 2e^2 - 2 \\approx 12{,}78$.",
    timeLimitSeconds: 150 },
  { category: "nationella_3c", tier: "Diamond", difficultyElo: 2250,
    prompt: "**NP Ma3c HT 2013 · 15.** Bestäm konstanten $A$ så att $\\displaystyle \\lim_{x \\to \\infty} \\dfrac{A x}{4 x + A} = \\dfrac{1}{7}$.",
    answerType: "numeric", correctAnswer: "0.571",
    acceptableForms: ["4/7"], tolerance: 0.01,
    solution: "$\\lim = A/4 = 1/7 \\Rightarrow A = 4/7 \\approx 0{,}571$.",
    timeLimitSeconds: 150 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1900,
    prompt: "**NP Ma3c HT 2013 · 16.** För vilket positivt värde på $x$ har grafen till $f(x) = x^3 - 0{,}88 x$ lutningen $5$?",
    answerType: "numeric", correctAnswer: "1.4",
    tolerance: 0.02,
    solution: "$f'(x) = 3x^2 - 0{,}88 = 5 \\Rightarrow x^2 = 1{,}96 \\Rightarrow x = 1{,}4$ (positiv rot).",
    timeLimitSeconds: 120 },
  { category: "nationella_3c", tier: "Diamond", difficultyElo: 2080,
    prompt: "**NP Ma3c HT 2013 · 20a.** En modell för antalet människor på jorden är $N(t) = \\dfrac{11}{1 + 3{,}4 e^{-0{,}03 t}}$ (miljarder), där $t$ är år efter 1950. Bestäm antalet människor år 1950.",
    answerType: "numeric", correctAnswer: "2.5",
    tolerance: 0.05,
    solution: "$N(0) = 11/(1 + 3{,}4) = 11/4{,}4 = 2{,}5$ miljarder.",
    timeLimitSeconds: 90 },
  { category: "nationella_3c", tier: "Diamond", difficultyElo: 2120,
    prompt: "**NP Ma3c HT 2013 · 20b.** Med samma modell $N(t) = \\dfrac{11}{1 + 3{,}4 e^{-0{,}03 t}}$, bestäm den övre gränsen för antalet människor (i miljarder).",
    answerType: "numeric", correctAnswer: "11",
    solution: "När $t \\to \\infty$ går nämnaren mot $1$, så $N \\to 11$.",
    timeLimitSeconds: 90 },

  // ───── Extra NP-style problems modelled on the same topic distribution ─────
  // Same difficulty range, same Del B / Del C / Del D feel, but new prompts so
  // the same problem isn't recycled inside a single match.

  { category: "nationella_3c", tier: "Silver", difficultyElo: 1320,
    prompt: "Bestäm derivatan av $f(x) = 4x^3 - 9x + 2$ vid $x = 1$.",
    answerType: "numeric", correctAnswer: "3",
    solution: "$f'(x) = 12 x^2 - 9$; $f'(1) = 3$.",
    timeLimitSeconds: 60 },
  { category: "nationella_3c", tier: "Silver", difficultyElo: 1380,
    prompt: "Förenkla så långt som möjligt: $\\dfrac{x^2 - 4}{x - 2}$ för $x \\ne 2$. Ange uttryckets värde vid $x = 5$.",
    answerType: "numeric", correctAnswer: "7",
    solution: "$\\dfrac{(x-2)(x+2)}{x-2} = x + 2$. Vid $x = 5$: $7$.",
    timeLimitSeconds: 60 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1460,
    prompt: "Bestäm derivatan av $f(x) = \\sin x + 2 \\cos x$ vid $x = 0$.",
    answerType: "numeric", correctAnswer: "1",
    solution: "$f'(x) = \\cos x - 2 \\sin x$; $f'(0) = 1$.",
    timeLimitSeconds: 75 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1520,
    prompt: "Beräkna $\\displaystyle \\int_0^{3} (2x + 1)\\,dx$.",
    answerType: "numeric", correctAnswer: "12",
    solution: "$[x^2 + x]_0^3 = 9 + 3 = 12$.",
    timeLimitSeconds: 60 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1580,
    prompt: "Lös ekvationen $\\log_{10}(x) = 2$.",
    answerType: "numeric", correctAnswer: "100",
    solution: "$x = 10^2 = 100$.",
    timeLimitSeconds: 45 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1620,
    prompt: "En population växer enligt $P(t) = 500 \\cdot 1{,}05^t$. Hur stor är populationen efter $10$ år? Avrunda till heltal.",
    answerType: "numeric", correctAnswer: "814",
    tolerance: 2,
    solution: "$P(10) = 500 \\cdot 1{,}05^{10} \\approx 500 \\cdot 1{,}6289 \\approx 814$.",
    timeLimitSeconds: 90 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1660,
    prompt: "Funktionen $f(x) = 2 x^2 - 8 x + 3$ har ett minimum. Bestäm minimivärdet.",
    answerType: "numeric", correctAnswer: "-5",
    solution: "Symmetrilinje $x = 2$. $f(2) = 8 - 16 + 3 = -5$.",
    timeLimitSeconds: 75 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1720,
    prompt: "Bestäm derivatan av $g(x) = (3x + 1)^4$ vid $x = 0$.",
    answerType: "numeric", correctAnswer: "12",
    solution: "Kedjeregeln: $g'(x) = 12(3x+1)^3$; $g'(0) = 12$.",
    timeLimitSeconds: 75 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1780,
    prompt: "Beräkna $\\displaystyle \\int_1^{e} \\dfrac{1}{x}\\,dx$.",
    answerType: "numeric", correctAnswer: "1",
    solution: "$[\\ln x]_1^e = 1 - 0 = 1$.",
    timeLimitSeconds: 60 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1830,
    prompt: "Lös ekvationen $3 \\cdot 2^x = 48$.",
    answerType: "numeric", correctAnswer: "4",
    solution: "$2^x = 16 = 2^4$, så $x = 4$.",
    timeLimitSeconds: 60 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1870,
    prompt: "Funktionen $f(x) = x^3 - 12 x$ har ett lokalt maximum. Bestäm $x$-värdet där maximum antas (det negativa kritiska värdet).",
    answerType: "numeric", correctAnswer: "-2",
    solution: "$f'(x) = 3x^2 - 12 = 0 \\Rightarrow x = \\pm 2$. $f''(x) = 6x$; vid $x=-2$ är $f''<0$, alltså max.",
    timeLimitSeconds: 120 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1910,
    prompt: "En läkemedelskoncentration i blodet ges av $C(t) = 8 e^{-0{,}2 t}$ mg/L. Efter hur många timmar är koncentrationen $4$ mg/L? Avrunda till en decimal.",
    answerType: "numeric", correctAnswer: "3.5",
    tolerance: 0.1,
    solution: "$e^{-0{,}2 t} = 1/2 \\Rightarrow t = \\ln 2 / 0{,}2 \\approx 3{,}47$.",
    timeLimitSeconds: 120 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1960,
    prompt: "Beräkna arean mellan $y = x^2$ och $y = 2x$ för $x \\ge 0$.",
    answerType: "numeric", correctAnswer: "1.333",
    acceptableForms: ["4/3"], tolerance: 0.01,
    solution: "Skärningspunkter $x = 0, 2$. $\\int_0^2 (2x - x^2)\\,dx = [x^2 - x^3/3]_0^2 = 4 - 8/3 = 4/3$.",
    timeLimitSeconds: 150 },
  { category: "nationella_3c", tier: "Diamond", difficultyElo: 2010,
    prompt: "Bestäm derivatan av $h(x) = \\ln(3x)$ vid $x = 2$. Ange exakt värde.",
    answerType: "numeric", correctAnswer: "0.5",
    acceptableForms: ["1/2"], tolerance: 1e-3,
    solution: "$h'(x) = 1/x$, så $h'(2) = 1/2$.",
    timeLimitSeconds: 90 },
  { category: "nationella_3c", tier: "Diamond", difficultyElo: 2060,
    prompt: "Beräkna $\\displaystyle \\int_0^{1} 3 e^{3x}\\,dx$. Avrunda till två decimaler.",
    answerType: "numeric", correctAnswer: "19.09",
    tolerance: 0.05,
    solution: "$[e^{3x}]_0^1 = e^3 - 1 \\approx 19{,}09$.",
    timeLimitSeconds: 120 },
  { category: "nationella_3c", tier: "Diamond", difficultyElo: 2110,
    prompt: "En kropp rör sig med hastigheten $v(t) = 3 t^2 - 6 t$ m/s. Bestäm den totala sträckan kroppen färdas mellan $t = 0$ och $t = 3$ sekunder (sträcka, inte position).",
    answerType: "numeric", correctAnswer: "8",
    solution: "$v=0$ vid $t=0, 2$. $\\int_0^2 |v|\\,dt = -[t^3-3t^2]_0^2 = -(8-12) = 4$. $\\int_2^3 v\\,dt = [t^3-3t^2]_2^3 = 0-(-4) = 4$. Totalt: $8$ m.",
    timeLimitSeconds: 180 },
  { category: "nationella_3c", tier: "Diamond", difficultyElo: 2170,
    prompt: "Funktionen $f(x) = x e^{-x}$ har en maximalpunkt. Bestäm funktionens maximala värde. Avrunda till tre decimaler.",
    answerType: "numeric", correctAnswer: "0.368",
    acceptableForms: ["1/e"], tolerance: 0.005,
    solution: "$f'(x) = e^{-x}(1-x) = 0 \\Rightarrow x = 1$. $f(1) = 1/e \\approx 0{,}368$.",
    timeLimitSeconds: 150 },
  { category: "nationella_3c", tier: "Diamond", difficultyElo: 2220,
    prompt: "Lös ekvationen $\\ln(x^2) = 4$. Bestäm den positiva roten. Avrunda till två decimaler.",
    answerType: "numeric", correctAnswer: "7.39",
    acceptableForms: ["e^2"], tolerance: 0.02,
    solution: "$x^2 = e^4$, positiv rot $x = e^2 \\approx 7{,}39$.",
    timeLimitSeconds: 90 },
  { category: "nationella_3c", tier: "Master", difficultyElo: 2380,
    prompt: "En cylinder med given mantelyta $M = 100\\pi$ cm² ska ha så stor volym som möjligt. Bestäm cylinderns radie (cm). Avrunda till två decimaler.",
    answerType: "numeric", correctAnswer: "4.08",
    tolerance: 0.1,
    solution: "$M = 2\\pi r^2 + 2\\pi r h = 100\\pi \\Rightarrow h = 50/r - r$. $V(r) = \\pi r^2 h = 50\\pi r - \\pi r^3$. $V'(r) = 50\\pi - 3\\pi r^2 = 0 \\Rightarrow r = \\sqrt{50/3} \\approx 4{,}08$.",
    timeLimitSeconds: 300 },
  { category: "nationella_3c", tier: "Master", difficultyElo: 2420,
    prompt: "För vilket värde på $a$ tangerar linjen $y = a x$ kurvan $y = e^x$? Avrunda till tre decimaler.",
    answerType: "numeric", correctAnswer: "2.718",
    acceptableForms: ["e"], tolerance: 0.01,
    solution: "Vid tangenspunkten gäller $a x = e^x$ och $a = e^x$. Dela: $x = 1$, så $a = e \\approx 2{,}718$.",
    timeLimitSeconds: 300 },

  // ───── More NP-extracted problems (HT 2012, HT 2015, HT 2016, VT 2017) ─────

  // ── NpMa3c HT 2012 ──
  { category: "nationella_3c", tier: "Silver", difficultyElo: 1200,
    prompt: "**NP Ma3c HT 2012 · 1.** På tallinjen är $x_1 = -4$ och $x_2 = 1$ markerade. Bestäm $|x_1 - x_2|$.",
    answerType: "numeric", correctAnswer: "5",
    solution: "$|-4 - 1| = |-5| = 5$.",
    timeLimitSeconds: 45 },
  { category: "nationella_3c", tier: "Silver", difficultyElo: 1300,
    prompt: "**NP Ma3c HT 2012 · 2.** För vilket värde på $x$ är uttrycket $\\dfrac{3x - 21}{6 - x}$ inte definierat?",
    answerType: "numeric", correctAnswer: "6",
    solution: "Nämnaren $6 - x = 0 \\Rightarrow x = 6$.",
    timeLimitSeconds: 45 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1450,
    prompt: "**NP Ma3c HT 2012 · 3.** Vilket av alternativen visar ett polynom?",
    answerType: "multiple_choice", correctAnswer: "4x^3 + 2x^2",
    options: ["4/x^3 + 4x^3", "x^2 + x^{2.5}", "(2 + 1/x)^3", "4x^3 + 2x^2"],
    solution: "Ett polynom har bara icke-negativa heltalsexponenter. Endast $4x^3 + 2x^2$ uppfyller det.",
    timeLimitSeconds: 60 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1520,
    prompt: "**NP Ma3c HT 2012 · 4.** För vilken minsta positiva vinkel $v$ i intervallet $0^\\circ \\le v < 360^\\circ$ gäller att $\\sin v = \\dfrac{1}{2}$?",
    answerType: "numeric", correctAnswer: "30",
    solution: "$\\sin 30^\\circ = 1/2$. Den andra lösningen i intervallet är $150^\\circ$.",
    timeLimitSeconds: 60 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1480,
    prompt: "**NP Ma3c HT 2012 · 6.** Vilket av alternativen beskrivs bäst med en diskret funktion?",
    answerType: "multiple_choice", correctAnswer: "Intäkten beror av hur många stolar som tillverkas",
    options: [
      "Bensinförbrukningen hos en bil beror av hur långt bilen körs",
      "Volymen av en kub beror av sidans längd",
      "Intäkten beror av hur många stolar som tillverkas",
      "Kostnaden för bananer beror av vikten på bananerna",
    ],
    solution: "Antalet stolar är ett heltal — diskret variabel. De övriga är kontinuerliga.",
    timeLimitSeconds: 60 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1560,
    prompt: "**NP Ma3c HT 2012 · 9a.** Bestäm $\\displaystyle \\lim_{x \\to 0} (e^x + 7)$.",
    answerType: "numeric", correctAnswer: "8",
    solution: "Insättning: $e^0 + 7 = 1 + 7 = 8$.",
    timeLimitSeconds: 45 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1820,
    prompt: "**NP Ma3c HT 2012 · 9b.** Bestäm $\\displaystyle \\lim_{x \\to \\infty} \\sqrt{\\dfrac{16 x}{4 x + 9}}$.",
    answerType: "numeric", correctAnswer: "2",
    solution: "Bråket går mot $16/4 = 4$, och $\\sqrt{4} = 2$.",
    timeLimitSeconds: 90 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1880,
    prompt: "**NP Ma3c HT 2012 · 10.** Använd enhetscirkeln och bestäm $\\cos(180^\\circ - v)$ om $\\sin v = 0{,}8$ (och $v$ ligger i första kvadranten).",
    answerType: "numeric", correctAnswer: "-0.6",
    tolerance: 0.01,
    solution: "$\\cos v = 0{,}6$. Då gäller $\\cos(180^\\circ - v) = -\\cos v = -0{,}6$.",
    timeLimitSeconds: 90 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1580,
    prompt: "**NP Ma3c HT 2012 · 11.** Beräkna $\\displaystyle \\int_1^{2} 6 x^2\\,dx$ algebraiskt.",
    answerType: "numeric", correctAnswer: "14",
    solution: "$[2 x^3]_1^2 = 16 - 2 = 14$.",
    timeLimitSeconds: 75 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1780,
    prompt: "**NP Ma3c HT 2012 · 12.** För funktionen $f$ gäller att $f(x) = x^3 - 3 x^2$. Bestäm funktionens minsta värde inom intervallet där $f'(x) = 0$.",
    answerType: "numeric", correctAnswer: "-4",
    solution: "$f'(x) = 3 x^2 - 6 x = 0 \\Rightarrow x = 0, 2$. $f(0) = 0$ (max), $f(2) = -4$ (min).",
    timeLimitSeconds: 120 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1620,
    prompt: "**NP Ma3c HT 2012 · 13a.** För $f(x) = 5 x^2 + 3 x$, bestäm det $x$ där grafen har lutningen $18$.",
    answerType: "numeric", correctAnswer: "1.5",
    acceptableForms: ["3/2", "1.5"], tolerance: 0.01,
    solution: "$f'(x) = 10 x + 3 = 18 \\Rightarrow x = 1{,}5$.",
    timeLimitSeconds: 60 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1740,
    prompt: "**NP Ma3c HT 2012 · 14a.** Förenkla $\\dfrac{(x-3)(x+2)}{2x - 6}$ och ange uttryckets värde vid $x = 4$.",
    answerType: "numeric", correctAnswer: "3",
    solution: "$\\dfrac{(x-3)(x+2)}{2(x-3)} = \\dfrac{x+2}{2}$. Vid $x=4$: $3$.",
    timeLimitSeconds: 75 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1880,
    prompt: "**NP Ma3c HT 2012 · 17.** Bestäm det värde på $x$ där derivatan till $f(x) = x^2 + 5x$ är lika med derivatan till $g(x) = -5x^2 + 14x$.",
    answerType: "numeric", correctAnswer: "0.75",
    acceptableForms: ["3/4"], tolerance: 0.01,
    solution: "$f'(x) = 2x + 5$, $g'(x) = -10x + 14$. $2x + 5 = -10x + 14 \\Rightarrow 12 x = 9 \\Rightarrow x = 0{,}75$.",
    timeLimitSeconds: 120 },

  // ── NpMa3c HT 2015 ──
  { category: "nationella_3c", tier: "Silver", difficultyElo: 1100,
    prompt: "**NP Ma3c HT 2015 · 1.** Beräkna $|5 - 8|$.",
    answerType: "numeric", correctAnswer: "3",
    solution: "$|5 - 8| = |-3| = 3$.",
    timeLimitSeconds: 30 },
  { category: "nationella_3c", tier: "Silver", difficultyElo: 1280,
    prompt: "**NP Ma3c HT 2015 · 3.** För vilket värde på $x$ är uttrycket $\\dfrac{2x + 10}{3x - 6}$ inte definierat?",
    answerType: "numeric", correctAnswer: "2",
    solution: "$3x - 6 = 0 \\Rightarrow x = 2$.",
    timeLimitSeconds: 45 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1550,
    prompt: "**NP Ma3c HT 2015 · 6a.** Vilken vinkel ger störst värde på $\\sin v$?",
    answerType: "multiple_choice", correctAnswer: "sin 80°",
    options: ["sin 40°", "sin 80°", "sin 120°", "sin 200°"],
    solution: "$\\sin 80^\\circ \\approx 0{,}985$ — det största värdet av alternativen.",
    timeLimitSeconds: 60 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1600,
    prompt: "**NP Ma3c HT 2015 · 6b.** Vilken vinkel ger minst värde på $\\sin v$?",
    answerType: "multiple_choice", correctAnswer: "sin 280°",
    options: ["sin 160°", "sin 200°", "sin 240°", "sin 280°"],
    solution: "$\\sin 280^\\circ \\approx -0{,}985$ — det minsta (mest negativa) värdet.",
    timeLimitSeconds: 60 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1900,
    prompt: "**NP Ma3c HT 2015 · 9.** Bestäm $\\displaystyle \\lim_{x \\to 0} \\dfrac{\\ln e^x + x e^x}{5 x}$.",
    answerType: "numeric", correctAnswer: "0.4",
    acceptableForms: ["2/5", "0.4"], tolerance: 0.01,
    solution: "$\\ln e^x = x$, så täljaren $= x + x e^x = x(1 + e^x)$. Ratio $= (1 + e^x)/5 \\to 2/5$ när $x \\to 0$.",
    timeLimitSeconds: 120 },
  { category: "nationella_3c", tier: "Diamond", difficultyElo: 2150,
    prompt: "**NP Ma3c HT 2015 · 11.** Derivatan till $f(x) = \\sqrt{\\pi} \\cdot \\sqrt{x}$ kan skrivas på formen $f'(x) = \\sqrt{\\dfrac{\\pi}{a x}}$. Bestäm konstanten $a$.",
    answerType: "numeric", correctAnswer: "4",
    solution: "$f(x) = \\sqrt{\\pi x}$, så $f'(x) = \\dfrac{\\sqrt{\\pi}}{2\\sqrt{x}} = \\sqrt{\\dfrac{\\pi}{4x}}$. Alltså $a = 4$.",
    timeLimitSeconds: 150 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1500,
    prompt: "**NP Ma3c HT 2015 · 14a.** Beräkna $\\displaystyle \\int_0^{3} (x^2 - 2)\\,dx$ algebraiskt.",
    answerType: "numeric", correctAnswer: "3",
    solution: "$[x^3/3 - 2x]_0^3 = 9 - 6 = 3$.",
    timeLimitSeconds: 75 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1820,
    prompt: "**NP Ma3c HT 2015 · 14b.** Beräkna $\\displaystyle \\int_1^{2} \\left(x + \\dfrac{1}{x^3}\\right)\\,dx$ algebraiskt.",
    answerType: "numeric", correctAnswer: "1.875",
    acceptableForms: ["15/8"], tolerance: 0.01,
    solution: "$\\left[\\dfrac{x^2}{2} - \\dfrac{1}{2x^2}\\right]_1^2 = (2 - 1/8) - (1/2 - 1/2) = 15/8 = 1{,}875$.",
    timeLimitSeconds: 120 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1900,
    prompt: "**NP Ma3c HT 2015 · 15.** Lös ekvationen $\\dfrac{3}{9 - 3x} = \\dfrac{1}{3} - \\dfrac{2}{3 - x}$.",
    answerType: "numeric", correctAnswer: "-6",
    solution: "$\\dfrac{3}{3(3-x)} = \\dfrac{1}{3-x}$. Ekvationen ger $\\dfrac{1}{3-x} + \\dfrac{2}{3-x} = \\dfrac{1}{3}$, dvs $\\dfrac{3}{3-x} = \\dfrac{1}{3}$, så $3-x = 9$ och $x = -6$.",
    timeLimitSeconds: 180 },
  { category: "nationella_3c", tier: "Diamond", difficultyElo: 2100,
    prompt: "**NP Ma3c HT 2015 · 21a.** Föreningen Lyckan har medlemmar enligt $f(t) = 1250 \\cdot e^{0{,}012 t}$, $t$ år efter 2010. Vilket år har föreningen 2000 medlemmar?",
    answerType: "numeric", correctAnswer: "2049",
    tolerance: 1,
    solution: "$1250 e^{0{,}012 t} = 2000 \\Rightarrow e^{0{,}012 t} = 1{,}6$, $t = \\ln(1{,}6)/0{,}012 \\approx 39{,}2$. År $= 2010 + 39 = 2049$.",
    timeLimitSeconds: 180 },

  // ── NpMa3c HT 2016 ──
  { category: "nationella_3c", tier: "Silver", difficultyElo: 1180,
    prompt: "**NP Ma3c HT 2016 · 1.** En bil kör 300 km på 5 timmar. Bestäm bilens medelhastighet i km/h.",
    answerType: "numeric", correctAnswer: "60",
    solution: "$v = 300/5 = 60$ km/h.",
    timeLimitSeconds: 30 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1480,
    prompt: "**NP Ma3c HT 2016 · 2.** Cirkeln har ekvationen $(x+1)^2 + (y - A)^2 = 4$. Cirkelns centrum är vid $(-1, 3)$. Bestäm $A$.",
    answerType: "numeric", correctAnswer: "3",
    solution: "Centrum är $(-1, A)$, alltså $A = 3$.",
    timeLimitSeconds: 60 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1530,
    prompt: "**NP Ma3c HT 2016 · 3a.** För $f(x) = e^{4x}$, bestäm ett närmevärde till $f(0{,}25)$. Svara med en decimal.",
    answerType: "numeric", correctAnswer: "2.7",
    tolerance: 0.05,
    solution: "$f(0{,}25) = e^1 = e \\approx 2{,}7$.",
    timeLimitSeconds: 60 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1610,
    prompt: "**NP Ma3c HT 2016 · 4a.** Punkten $P = (3/5, 4/5)$ ligger på enhetscirkeln och bildar vinkeln $v$ med positiva $x$-axeln. Vilket värde har $\\sin v$?",
    answerType: "multiple_choice", correctAnswer: "4/5",
    options: ["3/4", "3/5", "4/5", "5/4"],
    solution: "Punkten $P$ har $y$-koordinaten $4/5$, alltså $\\sin v = 4/5$.",
    timeLimitSeconds: 60 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1660,
    prompt: "**NP Ma3c HT 2016 · 4b.** Med samma $P = (3/5, 4/5)$, vilket värde har $\\tan v$?",
    answerType: "multiple_choice", correctAnswer: "4/3",
    options: ["4/3", "3/4", "3/5", "5/3"],
    solution: "$\\tan v = \\sin v / \\cos v = (4/5)/(3/5) = 4/3$.",
    timeLimitSeconds: 60 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1750,
    prompt: "**NP Ma3c HT 2016 · 11.** Pandans vikt ges av $V(x) = -5 x^2 + 40 x + 0{,}1$ (kg, år). Bestäm $V'(2)$ (viktökningshastighet vid år $2$).",
    answerType: "numeric", correctAnswer: "20",
    solution: "$V'(x) = -10 x + 40$. $V'(2) = 20$ kg/år.",
    timeLimitSeconds: 75 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1840,
    prompt: "**NP Ma3c HT 2016 · 12.** För $f(x) = 2 x^3 - 24 x$, vad är funktionens lokala maximivärde?",
    answerType: "numeric", correctAnswer: "32",
    solution: "$f'(x) = 6 x^2 - 24 = 0 \\Rightarrow x = \\pm 2$. Vid $x = -2$: $f''(-2) = -24 < 0$ → max. $f(-2) = -16 + 48 = 32$.",
    timeLimitSeconds: 120 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1840,
    prompt: "**NP Ma3c HT 2016 · 12.** För $f(x) = 2 x^3 - 24 x$, vad är funktionens lokala minimivärde?",
    answerType: "numeric", correctAnswer: "-32",
    solution: "Vid $x = 2$: $f''(2) = 24 > 0$ → min. $f(2) = 16 - 48 = -32$.",
    timeLimitSeconds: 120 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1530,
    prompt: "**NP Ma3c HT 2016 · 13a.** Beräkna algebraiskt $\\displaystyle \\int_1^{2} (3 x^2 + 5)\\,dx$.",
    answerType: "numeric", correctAnswer: "12",
    solution: "$[x^3 + 5x]_1^2 = (8 + 10) - (1 + 5) = 12$.",
    timeLimitSeconds: 60 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1780,
    prompt: "**NP Ma3c HT 2016 · 13b.** Beräkna algebraiskt $\\displaystyle \\int_{-4}^{-2} \\dfrac{4}{x^2}\\,dx$.",
    answerType: "numeric", correctAnswer: "1",
    solution: "$\\int 4/x^2\\,dx = -4/x$. $[-4/x]_{-4}^{-2} = 2 - 1 = 1$.",
    timeLimitSeconds: 90 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1900,
    prompt: "**NP Ma3c HT 2016 · 15.** För $f(x) = 1/\\sqrt{x}$ ska du bestämma den primitiva funktionen $F$ med $F(9) = 10$. Bestäm $F(16)$.",
    answerType: "numeric", correctAnswer: "12",
    solution: "$F(x) = 2\\sqrt{x} + C$. $F(9) = 6 + C = 10 \\Rightarrow C = 4$. $F(16) = 8 + 4 = 12$.",
    timeLimitSeconds: 120 },
  { category: "nationella_3c", tier: "Diamond", difficultyElo: 2050,
    prompt: "**NP Ma3c HT 2016 · 19.** För $f(x) = x^2 - 24 x$, bestäm värdet på $a$ så att $f'(a) = 17$.",
    answerType: "numeric", correctAnswer: "20.5",
    tolerance: 0.01,
    solution: "$f'(x) = 2x - 24 = 17 \\Rightarrow x = 20{,}5$.",
    timeLimitSeconds: 90 },

  // ── NpMa3c VT 2017 ──
  { category: "nationella_3c", tier: "Silver", difficultyElo: 1100,
    prompt: "**NP Ma3c VT 2017 · 1.** Bestäm $|-4 - 3|$.",
    answerType: "numeric", correctAnswer: "7",
    solution: "$|-7| = 7$.",
    timeLimitSeconds: 30 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1480,
    prompt: "**NP Ma3c VT 2017 · 3b.** För $f(x) = 3x^2 - 6x - 10$, bestäm $f'(1)$.",
    answerType: "numeric", correctAnswer: "0",
    solution: "$f'(x) = 6x - 6$. $f'(1) = 0$.",
    timeLimitSeconds: 60 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1550,
    prompt: "**NP Ma3c VT 2017 · 3c.** För $f(x) = 3x^2 - 6x - 10$, vilket alternativ är korrekt?",
    answerType: "multiple_choice", correctAnswer: "Grafen har en minimipunkt",
    options: [
      "Grafen har en terrasspunkt",
      "Grafen har en maximipunkt",
      "Grafen har en minimipunkt",
      "Grafen har en inflektionspunkt",
    ],
    solution: "Andragradsfunktion med positiv koefficient framför $x^2$ → öppnar uppåt → minimum.",
    timeLimitSeconds: 60 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1800,
    prompt: "**NP Ma3c VT 2017 · 7.** Använd formeln $a \\sin 40^\\circ = 52 \\sin 110^\\circ$ och bestäm $a$ avrundat till heltal.",
    answerType: "numeric", correctAnswer: "76",
    tolerance: 1,
    solution: "$a = 52 \\sin 110^\\circ / \\sin 40^\\circ = 52 \\cdot 0{,}9397 / 0{,}6428 \\approx 76$.",
    timeLimitSeconds: 90 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1880,
    prompt: "**NP Ma3c VT 2017 · 9.** En cirkel har medelpunkten i origo och arean $34\\pi$. Vad är $r^2$ (radien i kvadrat)?",
    answerType: "numeric", correctAnswer: "34",
    solution: "$\\pi r^2 = 34\\pi \\Rightarrow r^2 = 34$. Cirkelns ekvation: $x^2 + y^2 = 34$.",
    timeLimitSeconds: 60 },
  { category: "nationella_3c", tier: "Diamond", difficultyElo: 2150,
    prompt: "**NP Ma3c VT 2017 · 10.** Använd l'Hospitals regel för att bestämma $\\displaystyle \\lim_{x \\to 1} \\dfrac{x^7 - 1}{x^9 - 1}$. Avrunda till tre decimaler.",
    answerType: "numeric", correctAnswer: "0.778",
    acceptableForms: ["7/9"], tolerance: 0.01,
    solution: "Derivera täljare och nämnare: $\\dfrac{7 x^6}{9 x^8} \\to \\dfrac{7}{9} \\approx 0{,}778$.",
    timeLimitSeconds: 150 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1900,
    prompt: "**NP Ma3c VT 2017 · 13.** För $f(x) = 3 x^3 - 36 x$, vad är funktionens lokala maximivärde?",
    answerType: "numeric", correctAnswer: "48",
    solution: "$f'(x) = 9 x^2 - 36 = 0 \\Rightarrow x = \\pm 2$. Vid $x = -2$: $f''(-2) = -36 < 0$ → max. $f(-2) = -24 + 72 = 48$.",
    timeLimitSeconds: 120 },
  { category: "nationella_3c", tier: "Gold", difficultyElo: 1500,
    prompt: "**NP Ma3c VT 2017 · 14a.** Beräkna algebraiskt arean som begränsas av $x$-axeln, grafen till $f(x) = 9 x^2$ och linjen $x = 2$.",
    answerType: "numeric", correctAnswer: "24",
    solution: "$\\int_0^2 9 x^2\\,dx = [3 x^3]_0^2 = 24$.",
    timeLimitSeconds: 75 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1800,
    prompt: "**NP Ma3c VT 2017 · 14b.** Beräkna algebraiskt arean som begränsas av $x$-axeln, grafen till $f(x) = 3/x^2$ och linjerna $x = 1$ och $x = 4$.",
    answerType: "numeric", correctAnswer: "2.25",
    acceptableForms: ["9/4"], tolerance: 0.01,
    solution: "$\\int_1^4 3/x^2\\,dx = [-3/x]_1^4 = -3/4 + 3 = 9/4 = 2{,}25$.",
    timeLimitSeconds: 90 },
  { category: "nationella_3c", tier: "Platinum", difficultyElo: 1880,
    prompt: "**NP Ma3c VT 2017 · 15.** Funktionen $f$ är en rät linje med $f(0) = 4$ och $f(10) = 0$. $F$ är en primitiv funktion med $F(0) = 5$. Bestäm $F(10)$.",
    answerType: "numeric", correctAnswer: "25",
    solution: "$f(x) = 4 - 0{,}4 x$. $F(x) = 4x - 0{,}2 x^2 + 5$. $F(10) = 40 - 20 + 5 = 25$.",
    timeLimitSeconds: 150 },
  { category: "nationella_3c", tier: "Diamond", difficultyElo: 2120,
    prompt: "**NP Ma3c VT 2017 · 17.** Funktionen $f$ har derivatan $f'(x) = 3 x^2 + 1$. Undersök hur många reella lösningar ekvationen $f(x) = 0$ kan ha.",
    answerType: "numeric", correctAnswer: "1",
    solution: "$f'(x) > 0$ för alla $x$, så $f$ är strikt växande. $f$ antar varje värde exakt en gång, alltså har $f(x) = 0$ exakt $1$ lösning.",
    timeLimitSeconds: 180 },
  { category: "nationella_3c", tier: "Diamond", difficultyElo: 2230,
    prompt: "**NP Ma3c VT 2017 · 18.** Papegojpopulationen ges av $P(x) = 300 \\cdot 0{,}95^x - 20 A (0{,}95^x - 1)$ där $A$ är antalet som planteras ut varje år. Bestäm $A$ så att antalet med tiden närmar sig $500$.",
    answerType: "numeric", correctAnswer: "25",
    solution: "När $x \\to \\infty$ går $0{,}95^x \\to 0$, så $P \\to 0 - 20A \\cdot (-1) = 20 A$. Sätt $20 A = 500 \\Rightarrow A = 25$.",
    timeLimitSeconds: 240 },
];

async function main() {
  console.log("Seeding problems…");
  await prisma.problem.deleteMany({});

  for (const p of PROBLEMS) {
    await prisma.problem.create({
      data: {
        mode: "classic",
        category: p.category,
        tier: p.tier,
        difficultyElo: p.difficultyElo,
        prompt: p.prompt,
        answerType: p.answerType,
        correctAnswer: p.correctAnswer,
        acceptableForms: p.acceptableForms ? JSON.stringify(p.acceptableForms) : null,
        tolerance: p.tolerance ?? (p.answerType === "numeric" ? 1e-6 : 0),
        options: p.options ? JSON.stringify(p.options) : null,
        solution: p.solution,
        timeLimitSeconds: p.timeLimitSeconds,
        calculatorAllowed: p.calculatorAllowed ?? false,
        language: "en",
      },
    });
  }
  console.log(`Inserted ${PROBLEMS.length} problems.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
